dbt-demo:
  target: dev
  outputs:
    dev:
      dataset: dbt_cc
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dt-cecile-sandbox-dev
      threads: 4
      type: bigquery