name: Lint dbt Project on Push

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  # this job runs SQLFluff with a specific set of rules
  # details on linter rules: https://docs.sqlfluff.com/en/stable/rules.html
  lint_project:
    name: Run SQLFluff linter
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout branch
        uses: "actions/checkout@v3"

      - name: Install Python
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.10"

      - name: Install SQLFluff
        run: "python -m pip install sqlfluff"

      - name: Lint project
        run: "sqlfluff lint models --dialect bigquery"
