name: Lint dbt Project on Push

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  # this job runs SQLFluff with a specific set of rules
  # details on linter rules: https://docs.sqlfluff.com/en/stable/rules.html
  lint_project:
    name: Run SQLFluff linter
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install SQLFluff
        run: python -m pip install sqlfluff

      - name: Get changed SQL files in models directory
        id: changed-sql-files
        uses: tj-actions/changed-files@v45
        with:
          files: 'models/**/*.sql'
          separator: ' '

      - name: Lint changed SQL files
        if: steps.changed-sql-files.outputs.any_changed == 'true'
        run: |
          changed_files="${{ steps.changed-sql-files.outputs.all_changed_files }}"
          for file in $changed_files; do
            echo "Linting $file"
            sqlfluff lint "$file" --dialect bigquery --format github-annotation-native
          done
